# <font color="DarkCyan">CSE111-Midterm-Fall-2021</font>

# <font color='darkpink'> Question-1</font>
***Design the required class(es) to get the output shown from the driver code.\
Your code should work for any number of arguments in addStudent method of the SDS class.***


**Output:**\
School of Data and Sciences 2021! Only CSE and MNS department students can be added.
  
\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\
Number of CSE students: 0\
Number of MNS students: 0\
CSE Students {}\
MNS Students {}\
1.================================\
Name: Maliha\
ID: 21101001\
Department: MNS\
Courses: []\
CGPA: 0\
2.================================\
Number of CSE students: 0\
Number of MNS students: 1\
CSE Students {}\
MNS Students {21101001: ['Maliha', 0, []]}\
3.================================\
Name: Subha\
ID: 21301001\
Department: CSE\
Courses: ['ENG091', 'MAT092']\
CGPA: 3.48\
4.================================\
Number of CSE students: 1\
Number of MNS students: 1\
CSE Students {21301001: ['Subha', 3.48, ['ENG091', 'MAT092']]}\
MNS Students {21101001: ['Maliha', 0, []]}\
5.================================\
6.================================\
Name: Samiul\
ID: 21305001\
Department: MNS\
Courses: ['ENG091', 'MAT092', 'PHY111']\
CGPA: 3.01\
7.================================\
Name: Mohsina\
ID: 21305023\
Department: MNS\
Courses: []\
CGPA: 0\
8.================================\
9.================================\
Number of CSE students: 1\
Number of MNS students: 3\
CSE Students {21301001: ['Subha', 3.48, ['ENG091', 'MAT092']]}\
MNS Students {21101001: ['Maliha', 0, []], 21305001: ['Samiul', 3.01, ['ENG091', 'MAT092', 'PHY111']], 21305023: ['Mohsina', 0, []]}\
10.================================\
BBS department student cannot be added to SDS\
11.================================\
Number of CSE students: 1\
Number of MNS students: 3\
CSE Students {21301001: ['Subha', 3.48, ['ENG091', 'MAT092']]}\
MNS Students {21101001: ['Maliha', 0, []], 21305001: ['Samiul', 3.01, ['ENG091', 'MAT092', 'PHY111']], 21305023: ['Mohsina', 0, []]}

In [ ]:
# Write you code here


#======================================================================
#Do not change the codes below
sds21 = SDS("2021")
print("*********************************************")
sds21.print_info()
print("1.================================")
s1 = Student("Maliha",21101001)
s1.print_info()
print("2.================================")
sds21.addStudent(s1)
sds21.print_info()
print("3.================================")
s2 = Student("Subha",21301001,"CSE", ["ENG091","MAT092"],3.48)
s2.print_info()
print("4.================================")
sds21.addStudent(s2)
sds21.print_info()
print("5.================================")
s3 = Student("Samiul",21305001,"MNS", ["ENG091","MAT092","PHY111"],3.01)
s4 = Student("Mohsina",21305023)
print("6.================================")
s3.print_info()
print("7.================================")
s4.print_info()
print("8.================================")
sds21.addStudent(s3,s4)
print("9.================================")
sds21.print_info()
print("10.================================")
s5 = Student("Nayla", 16101288, "BBS")
sds21.addStudent(s5)
print("11.================================")
sds21.print_info()

# <font color='darkpink'> Question-2</font>
***Design the required class(es) so that the following expected output is generated. Do not change any given code.\
Your code should work for any number of arguments in <font color='blue'>\_\_init_\_</font> and <font color='blue'>setToppings</font> method of pizza class. For simplicity,\
you can consider there will be only 3 categories of pizzas and they are: Chicken, Beef, Cheese.***


**Output:**\
Dominoâ€™s. The Pizza Delivery Experts.\
1.======================================\
2.======================================\
A pizza without toppings cannot be created.\
3.======================================\
Toppings added to Beef Kala Bhuna pizza.\
4.======================================\
5.======================================\
Total number of pizzas: 5\
Chicken Pizza:2\
Name:Spicy Chicken, Toppings: ['Spicy Chicken', 'Onion', 'Capsicum']\
Name:Chicken Dominator, Toppings: ['Barbecue Chicken,Spicy Chicken,Grilled Chicken']

Beef Pizza:2\
Name:Beef Kala Bhuna, Toppings: ['Curried Beef', 'Capsicum', 'Paprika', 'Onion']\
Name:Beefzza, Toppings: ['Minced Beef', 'Beef Pepperoni', 'Onion', 'Jalapeno']

Cheese Pizza: 1\
Name:Margherita, Toppings: ['Mozzarella Cheese']\
6.======================================

In [1]:
# Write you code here



#======================================================================
#Do not change the codes below
dom = Dominos("Domino's Pizza")
print("1.=================================")
p1 = Pizza("Spicy Chicken","Spicy Chicken","Onion","Capsicum")
dom.addPizza(p1)
p2 = Pizza("Margherita","Mozzarella Cheese")
print("2.=================================")
p3 = Pizza("Beef Kala Bhuna")
print("3.=================================")
p3.setToppings("Curried Beef","Capsicum","Paprika","Onion")
print("4.=================================")
dom.addPizza(p2,p3)
p4 = Pizza("Chicken Dominator","Barbecue Chicken,Spicy Chicken,Grilled Chicken")
p5 = Pizza("Beefzza","Minced Beef","Beef Pepperoni","Onion","Jalapeno")
dom.addPizza(p4,p5)
print("5.=================================")
dom.showMenu()
print("6.=================================")

NameError: name 'Dominos' is not defined

# <font color='darkpink'> Question-3</font>
***Design the required class(es) so that the following expected output is\
generated. Please use the following logic to calculateCost method.\
For each Forward the cost is 500\
For each Defender the cost is 450***


**Output:**\
1.============================================\
No players assigned yet\
2.============================================\
No cost yet as there is no players\
3.============================================\
Team Name: Argentina\
World Cup Win: 2\
Language: Spanish\
4.============================================\
5.============================================\
Total Cost: 1450\
6.============================================\
Team Name: Argentina\
World Cup Win: 2\
Language: Spanish\
Forwards:\
Messi\
Maria\
Defenders:\
Marcos\
7.============================================\
[('Messi', 'Forward'), ('Maria', 'Forward'), ('Marcos', 'Defender')]\
8.###############################################\
9.============================================\
No players assigned yet\
10.============================================\
No cost yet as there is no players\
11.============================================\
Team Name: Brazil\
World Cup Win: 5\
Language: Portuguese\
12.============================================\
13.============================================\
Total Cost: 950\
14.============================================\
Team Name: Brazil\
World Cup Win: 5\
Language: Portuguese\
Forwards:\
Neymar\
Defenders:\
Silva\
15.============================================\
[('Silva', 'Defender'), ('Neymar', 'Forward')]

In [ ]:
# Write you code here


#=======================================================
# Do not change the following lines of code.

argentina = Team("Argentina", 2)
print("1.============================================")
print(argentina.player_list)
print("2.============================================")
argentina.calculateCost()
print("3.============================================")
argentina.printDetail()
print("4.============================================")
messi = Player("Messi")
maria = Player("Maria")
marcos = Player("Marcos", "Defender")
argentina.addPlayer(messi)
argentina.addPlayer(maria)
argentina.addPlayer(marcos)
print("5.============================================")
argentina.calculateCost()
print("6.============================================")
argentina.printDetail()
print("7.============================================")
print(argentina.player_list)
print("8.###############################################")
brazil = Team("Brazil", 5, "Portuguese")
print("9.============================================")
print(brazil.player_list)
print("10.============================================")
brazil.calculateCost()
print("11.============================================")
brazil.printDetail()
print("12.============================================")
silva = Player("Silva", "Defender")
neymar = Player("Neymar")
brazil.addPlayer(silva)
brazil.addPlayer(neymar)
print("13.============================================")
brazil.calculateCost()
print("14.============================================")
brazil.printDetail()
print("15.============================================")
print(brazil.player_list)

# <font color='darkpink'> Question-4</font>

***Design the required class(es) so that the following expected output is\
generated. Do not change any given code.***


**Output:**\
1.===========================\
Sam has taken the Bus.\
2.===========================\
Calculating fare for Sam\
3.===========================\
Destination cannot be empty!\
4.===========================\
Destination of Bran is updated to Chittagong\
5.===========================\
John has taken the Bus.\
This is an Inter-City Bus. Bran cannot take the Bus.\
6.===========================\
Calculating fare for John\
7.===========================\
Mark has taken the Bus.\
This is an Inter-City Bus. Jack cannot take the Bus.\
8.===========================\
Calculating fare for Mark\
\===========================\
Details of Dhaka-123 Bus of SR Travels:\
Total Passengers: 3\
Passenger name : Sam, Destination: Dhaka, Ticket Price: 40\
Passenger name : John, Destination: Dhaka, Ticket Price: 40\
Passenger name : Mark, Destination: Dhaka, Ticket Price: 40\
9.===========================\
This is an Inter-City Car. Sam cannot take the Car.\
Bran has taken the Car.\
10.===========================\
Calculating fare for Bran\
11.===========================\
Details of Chittagong-798 Car of Uber:\
Total Passengers: 1\
Passenger name : Bran, Destination: Chittagong, Ticket Price: 250\
Jack has taken the Car.\
12.===========================\
Calculating fare for Jack\
13.===========================\
Details of Khulna-997 Car of Obhai:\
Total Passengers: 1\
Passenger name : Jack, Destination: Khulna, Ticket Price: 90

In [ ]:
# Write you code here



#=================================================
#Do not change the codes below

fareChart = {'SR Travels': 40, 'ENA': 50, 'Pathao': 200, 'Uber': 
250, 'Hanif Paribahan': 45, 'Others': 90 }
v1 = Vehicle("Dhaka-123", "Bus", 'SR Travels', fareChart)
p1 = Passenger("Sam", "Dhaka")
print("1.===========================")
v1.addPassenger(p1)
print("2.===========================")
p1.calculateFare(v1)
print("3.===========================")
p2 = Passenger("John", "Dhaka")
p3 = Passenger("Bran")
print("4.===========================")
p3.setDestination("Chittagong")
print("5.===========================")
v1.addPassenger(p2, p3)
print("6.===========================")
p2.calculateFare(v1)
print("7.===========================")
p4 = Passenger("Mark", "Dhaka")
p5 = Passenger("Jack", "Khulna")
v1.addPassenger(p4, p5)
print("8.===========================")
p4.calculateFare(v1)
print("===========================")
v1.status()
v2 = Vehicle("Chittagong-798", "Car", "Uber", fareChart)
print("9.===========================")
v2.addPassenger(p1)
v2.addPassenger(p3)
print("10.===========================")
p3.calculateFare(v2)
print("11.===========================")
v2.status()
v3 = Vehicle("Khulna-997", "Car", "Obhai", fareChart)
v3.addPassenger(p5)
print("12.===========================")
p5.calculateFare(v3)
print("13.===========================")
v3.status()

# <font color='darkpink'> Question-5</font>
***Design the required class(es) so that the following expected output is generated. Do not change any given code.\
Your code should work for any number of arguments in the serverPassenger() method.***

**Output:**\
Bob is waiting for Bus having 800 taka in pocket.\
Simon is waiting for Train having 950 taka in pocket.\
David is waiting for Train having 750 taka in pocket.\
Carol has 1500 taka in pocket.Please buy a ticket.\
1==============================\
This is a general bus and train ticket counter.\
2==============================\
Bob has bought Bus ticket.\
3==============================\
Simon has bought Train ticket.\
4==============================\
David has bought Train ticket.\
Carol please buy a ticket first.\
5==============================\
Carol has bought Train ticket.\
6==============================\
Total passengers:4\
Bus passengers:1\
Passenger Name:Bob Remaining balance:250\
Bus passengers:3\
Passenger Name:Simon Remaining balance:350\
Passenger Name:David Remaining balance:150\
Passenger Name:Carol Remaining balance:900

In [ ]:
# Write you code here

#===============================================
# Do not change the codes below
fareChart = {"Bus":550, "Train":600}
p1 = Passenger("Bob", "Bus Ticket",800)
p2 = Passenger("Simon", "Train Ticket", 950)
p3 = Passenger("David", "Train Ticket", 750)
p4 = Passenger("Carol", 1500)
print("1==============================")
tc = TicketCounter()
print("2==============================")
tc.servePassenger(p1,fareChart)
print("3==============================")
tc.servePassenger(p2,fareChart)
print("4==============================")
tc.servePassenger(p3, p4, fareChart)
print("5==============================")
p4.buyTicket("Train Ticket")
tc.servePassenger(p4,fareChart)
print("6==============================")
tc.showAllPassenger()

# <font color='darkpink'> Question-6</font>
***Design the required class(es) so that the following expected output is\
generated. Do not change any given code.***


**Output:**\
1.===========================\
Sam has taken the Bus.\
2.===========================\
Calculating fare for Sam\
3.===========================\
Destination cannot be empty!\
4.===========================\
Destination cannot be empty!\
5.===========================\
Destination of Bran is updated to Kakrail\
6.===========================\
John has taken the Bus.\
7.===========================\
Calculating fare for John\
8.===========================\
Bran has taken the Bus.\
9.===========================\
Calculating fare for Bran\
10.===========================\
Destination cannot be empty!\
11.===========================\
Bus is loaded. Mark cannot take the Bus.\
Bus is loaded. Jack cannot take the Bus.\
12.===========================\
Details of Dhaka-123 Bus:\
Total Passengers: 3\
Passenger name : Sam, Destination: Banani, Fare: 20\
Passenger name : John, Destination: Mohakhali, Fare: 30\
Passenger name : Bran, Destination: Kakrail, Fare: 60\
13.===========================\
Car is loaded. Sam cannot take the Car.\
Car is loaded. Bran cannot take the Car.\
14.===========================\
Details of Chittagong-798 Car:\
Total Passengers: 0

In [ ]:
# Write you code here




#====================================================================
# Do not change the codes below
fareChart = {'Banani': 2, 'Mohakhali':3, 'Mohammadpur':4, 'New 
Market':5, 'Others':6}
v1 = Vehicle("Dhaka-123", "Bus", 3)
p1 = Passenger("Sam", "Banani")
print("1.===========================")
v1.addPassenger(p1)
print("2.===========================")
p1.calculateFare(v1)
print("3.===========================")
p2 = Passenger("John", "Mohakhali")
p3 = Passenger("Bran")
print("4.===========================")
p3.setDestination()
print("5.===========================")
p3.setDestination("Kakrail")
print("6.===========================")
v1.addPassenger(p2)
print("7.===========================")
p2.calculateFare(v1)
print("8.===========================")
v1.addPassenger(p3)
print("9.===========================")
p3.calculateFare(v1)
p4 = Passenger("Mark", "Mohammadpur")
print("10.===========================")
p4.setDestination()
print("11.===========================")
v1.addPassenger(p4)
v1.addPassenger(Passenger("Jack", "New Market"))
print("12.===========================")
v1.details()
v2 = Vehicle("Chittagong-798", "Car", 0)
print("13.===========================")
v2.addPassenger(p1)
v2.addPassenger(p3)
print("14.===========================")
v2.details()

# <font color='darkpink'> Question-7</font>
***Design the required class(es) so that the following expected output is\
generated. Please use the following logic to calculateCost method.\
For each main character the cost is 10000\
For each supporting character the cost is 5000***


**Output:**\
1.============================================\
No characters assigned yet\
2.============================================\
No cost yet as there is no characters\
3.============================================\
Series Name: Sherlock Holmes\
Release Year: 2010\
Language: English\
4.============================================\
5.============================================\
Total Cost: 25000\
6.============================================\
Series Name: Sherlock Holmes\
Release Year: 2010\
Language: English\
Main Characters(s):\
Sherlock Holmes\
James Watson\
Supporting Characters(s):\
Irene Adler\
7.============================================\
[('Sherlock Holmes', 'Main character'), ('James Watson', 'Main character'), \
('Irene Adler', 'Supporting character')]\
8.###############################################\
9.============================================\
No characters assigned yet\
10.============================================\
No cost yet as there is no characters\
11.============================================\
Series Name: Squid Games\
Release Year: 2021\
Language: Korean\
12.============================================\
13.============================================\
Total Cost: 15000\
14.============================================\
Series Name: Squid Games\
Release Year: 2021\
Language: Korean\
Main Characters(s):\
Seong\
Supporting Characters(s):\
Kang\
15.============================================\
[('Seong', 'Main character'), ('Kang', 'Supporting character')]

In [ ]:
# Write you code here


#===================================================================
# You are not allowed to change any given code.
sherlock = Series("Sherlock Holmes", 2010)
print("1.============================================")
print(sherlock.character_list)
print("2.============================================")
sherlock.calculateCost()
print("3.============================================")
sherlock.printDetail()
print("4.============================================")
holmes = Character("Sherlock Holmes", "Main character")
watson = Character("James Watson", "Main character")
irene = Character("Irene Adler")
sherlock.addCharacter(holmes)
sherlock.addCharacter(watson)
sherlock.addCharacter(irene)
print("5.============================================")
sherlock.calculateCost()
print("6.============================================")
sherlock.printDetail()
print("7.============================================")
print(sherlock.character_list)
print("8.###############################################")
squid_games = Series("Squid Games", 2021, "Korean")
print("9.============================================")
print(squid_games.character_list)
print("10.============================================")
squid_games.calculateCost()
print("11.============================================")
squid_games.printDetail()
print("12.============================================")
seong = Character("Seong", "Main character")
kang = Character("Kang")
squid_games.addCharacter(seong)
squid_games.addCharacter(kang)
print("13.============================================")
squid_games.calculateCost()
print("14.============================================")
squid_games.printDetail()
print("15.============================================")
print(squid_games.character_list)

In [ ]:
#